[package]
name = "wedo-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.92"
axum = { version = "0.8.9" }
http = "1.5.0"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.53.1", features = ["full"] }
uuid = { version = "1.26.0", features = ["serde", "v4"] }
